global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
#  - "record-rules.yml"
#  - "alert-rules.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'ec2-nodes'
    static_configs:
      - targets: ["172.31.6.149:9090"]
